/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";

export class BadRequestError extends errors.FernWebsiteError {
    constructor() {
        super({
            message: "BadRequestError",
            statusCode: 400,
        });
        Object.setPrototypeOf(this, BadRequestError.prototype);
    }
}
