/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as FernWebsite from "../../../../../../api";
import * as core from "../../../../../../core";

export const BlogPostCollection: core.serialization.ObjectSchema<
    serializers.fixtures.BlogPostCollection.Raw,
    FernWebsite.fixtures.BlogPostCollection
> = core.serialization.object({
    items: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../../../..")).fixtures.BlogPost)
    ),
    total: core.serialization.number(),
    offset: core.serialization.number(),
    limit: core.serialization.number(),
});

export declare namespace BlogPostCollection {
    interface Raw {
        items: serializers.fixtures.BlogPost.Raw[];
        total: number;
        offset: number;
        limit: number;
    }
}
