/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as FernWebsite from "../../../../../../api";
import * as core from "../../../../../../core";

export const BlogPostSlug: core.serialization.Schema<
    serializers.fixtures.BlogPostSlug.Raw,
    FernWebsite.fixtures.BlogPostSlug
> = core.serialization.string();

export declare namespace BlogPostSlug {
    type Raw = string;
}
