/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../../../../../errors";
import * as FernWebsite from "../../../../../../..";

export class ArticleDoesNotExistError extends errors.FernWebsiteError {
    constructor(body: FernWebsite.fixtures.ArticleSlug) {
        super({
            message: "ArticleDoesNotExistError",
            statusCode: 404,
            body: body,
        });
        Object.setPrototypeOf(this, ArticleDoesNotExistError.prototype);
    }
}
