/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../../../../../core";
import { Article } from "../resources/article/client/Client";
import { Blogpost } from "../resources/blogpost/client/Client";

export declare namespace V1 {
    interface Options {
        environment: core.Supplier<string>;
        username?: core.Supplier<string | undefined>;
        password?: core.Supplier<string | undefined>;
    }
}

export class V1 {
    constructor(protected readonly options: V1.Options) {}

    protected _article: Article | undefined;

    public get article(): Article {
        return (this._article ??= new Article(this.options));
    }

    protected _blogpost: Blogpost | undefined;

    public get blogpost(): Blogpost {
        return (this._blogpost ??= new Blogpost(this.options));
    }
}
