/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The unique identifier for a blog post in the database, SEO-relevant
 *
 * @example
 *     "medical-advancements"
 */
export type BlogPostSlug = string;
