/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernWebsite from "../../../../..";

export interface CreateBlogPostRequest {
    slug: FernWebsite.fixtures.BlogPostSlug;
    title: string;
    author: string;
    image?: string;
    publicationeDate?: Date;
    richtext?: string;
}
