/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernWebsite from "../../../../..";

export interface ArticleCollection {
    items: FernWebsite.fixtures.Article[];
    total: number;
    offset: number;
    limit: number;
}
