/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The unique identifier for an article in the database, SEO-relevant
 *
 * @example
 *     "latest-developments-in-health-science"
 */
export type ArticleSlug = string;
