/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernWebsite from "../../../../..";

export interface CreatArticleRequest {
    slug: FernWebsite.fixtures.ArticleSlug;
    title: string;
    image?: string;
    publicationeDate?: Date;
    richtext?: string;
}
