/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../../../../../errors";
import * as FernWebsite from "../../../../../../..";

export class BlogPostDoesNotExistError extends errors.FernWebsiteError {
    constructor(body: FernWebsite.fixtures.BlogPostSlug) {
        super({
            message: "BlogPostDoesNotExistError",
            statusCode: 404,
            body: body,
        });
        Object.setPrototypeOf(this, BlogPostDoesNotExistError.prototype);
    }
}
