/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as FernWebsite from "../../../../../../api";
import * as core from "../../../../../../core";

export const ArticleSlug: core.serialization.Schema<
    serializers.fixtures.ArticleSlug.Raw,
    FernWebsite.fixtures.ArticleSlug
> = core.serialization.string();

export declare namespace ArticleSlug {
    type Raw = string;
}
